### ISSUE TITLE
 pandoc document conversion failed with error 137

### ISSUE THREAD

**Issue by thomasstjerne** [vmikk/PhyloNext#6]
I ran the pipeline and everything worked up until til the leaflet generation which failed with `pandoc document conversion failed with error 137` , any idea what this could be about?
Seems like it was the actual export of the Cloropleth.html file the errored

````
  Loading Biodiverse results
  ..Observed indices
  ..SES-scores
  ..P-values
  Preparing data for CANAPE analysis
  ..Running the CANAPE analysis
  ...Inferring endemism type
  Estimating sampling redundancy
  ..Loading a file with the total number of GBIF-records per H3-cell
  ..Adding N records to the main table
  ..Estimating the index
  Exporting the data table
  Preparing gridcell polygons
  ..Adding diversity estimates to polygons
  ..Adding H3 cell names
  ..Fixing antimeridian issue
  Creating leaflet map
  ..Generating polygon labels
  ..Building basemap
  ..Preparing color palettes
  ..Adding polygons
  ...  RICHNESS_ALL 
  ...  PD 
  ...  SES_PD 
  ...  PD_P 
  ...  ENDW_WE 
  ...  SES_ENDW_WE 
  ...  PE_WE 
  ...  SES_PE_WE 
  ... CANAPE
  ... Redundancy
  ..Adding variable selector
  ..Hiding variables
  ..Exporting the results
Command error:
  Killed
  Error: pandoc document conversion failed with error 137
  Execution halted

````

**Comment by thomasstjerne** [comment]
Memory issue?

**Comment by vmikk** [comment]
Hello Thomas! In the results, there should be a folder `pipeline_info`, which contains the execution trace and report. Could you please check how much memory this process used? It shouldn't be large, although it can consume >16GB RAM (depends on the number of grid cells in the dataset).

**Comment by thomasstjerne** [comment]
When I lowered `h3resolution` to 2 , the pipeline succeeded. I was running it with Joes Acacia tree on a GBIF download of all australian Fabaceae data.

**Comment by vmikk** [comment]
Could you please send me the entire folder (`wd/be/eeb65c...`)? There should be input data, log files, and the command itself.
Please note that there are hidden files and symlinks inside.
