### ISSUE TITLE
Add list of contributing GBIF datasets to output directory

### ISSUE THREAD

**Issue by thomasstjerne** [vmikk/PhyloNext#7]
In order to cite the filtered data used for a pipeline run, we would need a simple csv with two columns `datasetKey` and `occurrenceCount`.
This will allow a user (or the web GUI) to register a [derived dataset](https://www.gbif.org/derived-dataset/about) with a citable DOI.
I suggest to add it to the `pipeline_info` output directory.

**Comment by thomasstjerne** [comment]
Thanks @vmikk , that was fast!

**Comment by vmikk** [comment]
Currently there are no occurrence counts per dataset, as it's a bit tricky to get it (there were multiple rounds of filtering and spatial aggregation per species)

**Comment by thomasstjerne** [comment]
The dois / keys are the most important - if the counts are tricky, then we´ll just close it with the dois only
